---
title: "ReadMe"
format: html
editor: visual
---

## Intro

A converstation with Dave Cote led to him telling me about some unfinished otter work that he had been involved with. He sent me with "otter analysis notes" and "Otter camera paper" on 2024-08-20. On 2024-09-23, he sent me some data sets. I set up a github account and a Rproject. The original data sets are in the ../CAFE/projects/otterTNNP/original_data while the data files to be modified for analysis Rproject is in ../otterTNNP/otter-activity/data. The only modifications are changing the variable names and making .csv files

# Todo

-   fix doy in camera activity

-   get metadata

-   read thesis and see what was done - i'm sure I can do more and better although these days, maybe not

-   make months into dates, not characters

-   fix variable types in latrine data as they are all character - make sure they don't change

## Data

### metadata

Need some metadata for this

#### latrine_distributions

Talked to Cote. He said that this file was so that the latrine sites could be compared to random sites generated in GIS (Yolanda Wiersma was involved). Worksheets are divided into "all_sites", "depth sites", and original. I have added sheet 1 which was just to compare the data sets and a metadata page. The "original" is all the data, i.e., from TNNP and Alexander Bay containing latrine sites but also random sites but also sites that have the forage-area data which are not in the "all sites". I checked this on sheet 1 to confirm. Conclusion: work with "original"

### data clean up

This is going to take a lot of work!

Used readxl to bring data in. Got the following warning. the 'pm' is what is causing the problem followed by 2 blank values. I just deleted this in Excel but original data remains in folder outside of project (see above).

```         
Warning messages:
1: Expecting date in N1949 / R1949C14: got '12:79 pm'  
2: Expecting date in N13499 / R13499C14: got '16:35:00 PM'  
3: Expecting date in N13500 / R13500C14: got '16:37:00 PM' 
```

## Lawrence Thesis

What can we lift up; what new?

### Chatper 2 - Latrine site characteristics and patterns of activity

-   Landscape: A number of landscape variables (see Table 2.1) - forage area is not clearly defined;

    -   but its analysed with t-tests on log transformed data (assume ln but its not clear) to determine differences between latrine and random sites??? Suggest doing logistic regression on scaled/normalized/centered variables but need to know how to back-transform them

-   Latrine activity/preference

    -   autocorrelation not tested for

    -   used stepwise regression - really, results wouldn't change if you just did regular regression

        #### Thoughts: lift up/new

For landscape: suggest doing logistic regression on scaled/normalized/centered variables but need to know how to back-transform them

For latrine activity:

### Chapter 3:

-   used mixed-effects models

### Chapter 4: activity/groupsize \~ landscape type

Landscape type is a factor variable (used:Glovertown v unsued:NewmanSound)

## Analyses

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
